# Generated by Django 3.2.7 on 2021-10-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scoreboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat1', models.IntegerField(default=0)),
                ('stat2', models.IntegerField(default=0)),
                ('stat3', models.IntegerField(default=0)),
                ('stat4', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=10)),
                ('phoneNumber', models.IntegerField()),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('scoreboard', models.ManyToManyField(to='endpoint.Scoreboard')),
                ('user1', models.ManyToManyField(related_name='User_1', to='endpoint.User')),
                ('user2', models.ManyToManyField(related_name='User_2', to='endpoint.User')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scoreboard', models.ManyToManyField(to='endpoint.Scoreboard')),
                ('team1', models.ManyToManyField(related_name='Team_1', to='endpoint.Team')),
                ('team2', models.ManyToManyField(related_name='Team_2', to='endpoint.Team')),
            ],
        ),
    ]
