# Generated by Django 3.2.7 on 2021-10-19 00:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='team1',
            field=models.ManyToManyField(related_name='team1', to='endpoint.Team'),
        ),
        migrations.AlterField(
            model_name='game',
            name='team2',
            field=models.ManyToManyField(related_name='team2', to='endpoint.Team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='team',
            name='user1',
            field=models.ManyToManyField(related_name='user1', to='endpoint.User'),
        ),
        migrations.AlterField(
            model_name='team',
            name='user2',
            field=models.ManyToManyField(related_name='user2', to='endpoint.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstName',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastName',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=256),
        ),
    ]
